In [1]:
import os
import re
import random
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import signal

%matplotlib inline

In [2]:
loc = 'Test_Data/'
Test = pd.DataFrame()
Files = os.listdir(loc)

In [3]:
for i in range(len(Files)):

    cat_name = re.findall(r'(ZIF-\d+)\s.*.txt',Files[i])[0]

    with open(loc + Files[i],'r') as f:
        data = f.readlines()

    new_data = []
    for d in data:
        try:
            l = d.split()
            if l != []:
                new_data.append((float(l[0]), float(l[1])))
        except:
            l = d.split(',')
            if l != []:
                new_data.append((float(l[0]), float(l[1])))

    data = new_data

    X = [(lambda x: x[0])(d) for d in data]
    Y = [(lambda x: x[1])(d) for d in data]
    # Y = (Y - np.min(Y)) / (np.max(Y) - np.min(Y))
    
    df = {}
    for grid, value in zip(X, Y):
        df[grid] = [value]

    cols = [(lambda x: 'grid_' + str(x))(l) for l in X]
    Df = pd.DataFrame(df)
    Df.columns = cols

    Df['label'] = cat_name

    Test= pd.concat([Test, Df], axis = 0)

Test = Test.reset_index()
Test = Test.drop(['index'], axis = 1)
Test.head()

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,grid_10.0,grid_10.02,grid_10.04,grid_10.06,grid_10.08,grid_10.1,grid_10.12,grid_10.14,grid_10.16,grid_10.18,...,grid_9.82,grid_9.84,grid_9.86,grid_9.88,grid_9.9,grid_9.92,grid_9.94,grid_9.96,grid_9.98,label
0,2700.000,2903.330,2633.33,2773.330,2746.670,2930.00,3110.00,3116.670,3166.670,3220.000,...,2386.670,2516.670,2323.330,2330.0,2466.670,2513.330,2536.670,2590.000,2553.330,ZIF-67
1,2713.330,2766.670,2783.33,2946.670,3060.000,2946.67,3106.67,2933.330,2920.000,3220.000,...,2433.330,2473.330,2540.000,2490.0,2450.000,2643.330,2526.670,2610.000,2496.670,ZIF-67
2,1245.000,1445.000,1350.00,1365.000,1360.000,1580.00,1570.00,1475.000,1605.000,1605.000,...,1350.000,1190.000,1155.000,1070.0,1195.000,1310.000,1250.000,1250.000,1270.000,ZIF-67
3,436.667,416.667,420.00,446.667,513.333,460.00,430.00,516.667,466.667,503.333,...,396.667,340.000,350.000,330.0,370.000,423.333,353.333,426.667,343.333,ZIF-7
4,303.333,443.333,320.00,420.000,420.000,420.00,430.00,486.667,436.667,510.000,...,386.667,403.333,363.333,430.0,376.667,366.667,413.333,330.000,410.000,ZIF-7

In [4]:
with open('T_origin.pickle', 'wb') as f:
    pickle.dump(Test, f)